require("toyide.core.options")
require("toyide.core.keymappings").load_keymappings()
require("toyide.plugins")
require("toyide.colorscheme")
require("toyide.completion")
require("toyide.lsp")
require("toyide.telescope")